[package]
name = "rendering-fun"
version = "0.1.0"
authors = ["Trevor <trevor.h.crow@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.109.0"
rand = "0.7.3"